name: Deploy

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Setup Hexo
      run: |
        git config --global user.name 'howiezhao'
        git config --global user.email 'howiezhaohr@hotmail.com'
        git ls-files -z | while read -d '' path; do echo $path; done
        # git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done
        npm install -g hexo-cli
        npm install

    - name: Deploy
      run: |
        git clone https://github.com/howiezhao/howiezhao.github.io.git public
        hexo g
        cd public
        git status
        git diff 2017/06/20/hexo-experience/index.html
